#!/bin/bash
  
# Script:                       ops201d10-challenge08-windows-batch-scripting
# Author:                       Bryanna Fox
# Date of latest revision:      11/1/2023
# Purpose:                      Identify the script 


@echo off
setlocal enabledelayedexpansion

set /p sourcePath=Enter the source folder path:

set /p destinationPath=Enter the destination folder path:

if not exist "!sourcePath!\" (
    echo Error: Source folder does not exist.
    goto :eof
)

if not exist "!destinationPath!\" (
    echo Error: Destination folder does not exist.
    goto :eof
)

robocopy "!sourcePath!" "!destinationPath!" /E

if errorlevel 8 (
    echo Error: ROBOCOPY encountered errors during the copy operation.
) else (
    echo Copy operation completed successfully.
)

:end
endlocal

#in line 9 echo will display the following text in "". @echo off is telling the computer to NOT display ANY of the commands in the script.
#line 10, setlocal is saying to only look at a certian part of the script or narrowing the scope. enabledelayedexpansion is simply to enable a delayed expansion. 
#in line 12 set /p is telling the user to enter a value that will be assigned to sourcePath, from there that value will go into the source folder under path
 #line 14 is similar to line 14 it will ask the user to enter a value that will then be assigned to destinationPath and from there it will go into the destination folder under path
 #in line 20 if is the start of a loop. Line 20-21 is saying that if the value that is entered for the sourcePath does not exist then the command will show the message will display source folder does not exist. The goto :eof is signifying the end of the script and this will exit the script if there is no folder. 
  #line 28-30 is would be the same thing as 20-22 except this will apply to the destinationPath
 #line 26 the robocopy is telling the computer to copy a robust amount of information. the ! means delayed variable expansion that was enabled in line 11. the sourcePath destinationPath are the values that was entered from the user. the E/ at the end tells the robocopy to copy all the subdirectories including the empty ones.  
#line 39 opens another loop with if and it is telling the computer that if the error level is 8 or higher then line 40 will display an error message saying robocopy encountered errors during operations
  #line 41 is part of the loop commands telling the computer that if the  error level is lower than 8 then in line 42 the message will display that the copy operation was successful.
 #line 48 is saying that this is the end of the script and line 49 is indicating that it is the end of the local, this goes with the setlocal in line 11